-- Updated schema.sql for Cross-Platform Support
CREATE TABLE IF NOT EXISTS users (
    platform_id TEXT PRIMARY KEY, -- Can be Apple ID, Google ID, or Device ID
    platform_type TEXT,           -- 'apple', 'android', or 'guest'
    username VARCHAR(25) NOT NULL,
    rating_15_standard DOUBLE PRECISION DEFAULT 1500.0,
    rating_15_3s DOUBLE PRECISION DEFAULT 1500.0,
    rating_15_10s DOUBLE PRECISION DEFAULT 1500.0,
    rd DOUBLE PRECISION DEFAULT 350.0,
    wins INTEGER DEFAULT 0,
    losses INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. MATCHES TABLE
-- Adjusted to handle the room codes (strings) and UUIDs generated by your server
CREATE TABLE IF NOT EXISTS matches (
    id TEXT PRIMARY KEY, 
    host_username VARCHAR(25),
    guest_username VARCHAR(25),
    rule_set VARCHAR(20),
    vanish_ms INTEGER,
    board_size INTEGER,
    status VARCHAR(20) DEFAULT 'ongoing',
    winner VARCHAR(25),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. MOVES TABLE
-- Kept for game history/replays (ensure match_id type matches the matches table)
CREATE TABLE IF NOT EXISTS moves (
    id SERIAL PRIMARY KEY,
    match_id TEXT REFERENCES matches(id),
    username VARCHAR(25),
    row_idx INTEGER,
    col_idx INTEGER,
    placed_at_utc BIGINT
);